#!/usr/bin/env node
// Creates a local .env with freshly generated secrets. Never overwrites an existing file (it only adds
// APP_DB_PASSWORD to an older one that lacks it).
// Usage: node scripts/gen-env.mjs
import { randomBytes } from 'node:crypto';
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';

const target = new URL('../.env', import.meta.url);
if (existsSync(target)) {
  // An older .env is never regenerated (that would rotate the keys that protect stored data), but a value
  // introduced later can be added to it.
  const current = readFileSync(target, 'utf8');
  if (/^APP_DB_PASSWORD=./m.test(current)) {
    console.error('.env already exists and is complete — nothing to do.');
    process.exit(1);
  }
  appendFileSync(
    target,
    `${current.endsWith('\n') ? '' : '\n'}# Least-privilege role the API connects as (created by the migrate step, ADR-009).\nAPP_DB_PASSWORD=${randomBytes(24).toString('hex')}\n`,
  );
  console.log('Added APP_DB_PASSWORD to the existing .env (nothing else was changed).');
  process.exit(0);
}

const hex = (n) => randomBytes(n).toString('hex');
const pgPassword = hex(18);
const appDbPassword = hex(24);

writeFileSync(
  target,
  `# Generated by scripts/gen-env.mjs — local secrets, never commit.
NODE_ENV=development
LOG_LEVEL=info
PUBLIC_ORIGIN=http://localhost:5173

POSTGRES_PASSWORD=${pgPassword}
# Least-privilege role the API connects as (created by the migrate step, ADR-009). Never the owner password.
APP_DB_PASSWORD=${appDbPassword}
DATABASE_URL=postgres://mc:${pgPassword}@127.0.0.1:55432/mc
REDIS_URL=redis://127.0.0.1:56379

SESSION_SECRET=${hex(32)}
PII_ENCRYPTION_KEY=${randomBytes(32).toString('base64')}
PHONE_HASH_PEPPER=${hex(32)}

# ADR-004: console (OTP in API log) | demo-inbox (admin SMS inbox) | http (the organisers' own gateway)
SMS_PROVIDER=console
# console/demo-inbox need DEMO_MODE=true when NODE_ENV=production. Never set it at the real event.
DEMO_MODE=false
# SMS_PROVIDER=http only:
SMS_HTTP_URL=
SMS_HTTP_AUTH_HEADER=
SMS_HTTP_BODY_TEMPLATE=
# Extra browser origins allowed to POST (comma separated), e.g. http://localhost:8080
EXTRA_ORIGINS=

# Full Docker stack (pnpm stack:up)
STACK_NODE_ENV=development
STACK_PUBLIC_ORIGIN=http://localhost:8080
# Tunnel: Cloudflare named tunnel token (Zero Trust > Networks > Tunnels). Route hostname -> http://caddy:80
CLOUDFLARE_TUNNEL_TOKEN=
# Fallback tunnel (--profile tunnel-ngrok)
NGROK_AUTHTOKEN=
NGROK_DOMAIN=
`,
  { mode: 0o600 },
);
console.log('Wrote .env with fresh secrets (mode 600).');
