#!/usr/bin/env node
// Creates a local .env with freshly generated secrets. Never overwrites an existing file.
// Usage: node scripts/gen-env.mjs
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';

const target = new URL('../.env', import.meta.url);
if (existsSync(target)) {
  console.error(
    '.env already exists — refusing to overwrite. Delete it first if you really want new secrets.',
  );
  process.exit(1);
}

const hex = (n) => randomBytes(n).toString('hex');
const pgPassword = hex(18);

writeFileSync(
  target,
  `# Generated by scripts/gen-env.mjs — local secrets, never commit.
NODE_ENV=development
LOG_LEVEL=info
PUBLIC_ORIGIN=http://localhost:5173

POSTGRES_PASSWORD=${pgPassword}
DATABASE_URL=postgres://mc:${pgPassword}@127.0.0.1:55432/mc
REDIS_URL=redis://127.0.0.1:56379

SESSION_SECRET=${hex(32)}
PII_ENCRYPTION_KEY=${randomBytes(32).toString('base64')}
PHONE_HASH_PEPPER=${hex(32)}

# console = OTP printed to API logs (dev only). Set to twilio + credentials for the demo.
SMS_PROVIDER=console
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM=

# Full Docker stack (pnpm stack:up)
STACK_NODE_ENV=development
STACK_PUBLIC_ORIGIN=http://localhost:8080
# Tunnel (pnpm stack:up --profile tunnel): Cloudflare named-tunnel token, if using one
CLOUDFLARE_TUNNEL_TOKEN=
`,
  { mode: 0o600 },
);
console.log('Wrote .env with fresh secrets (mode 600).');
