#!/usr/bin/env node
// Creates a local .env with freshly generated secrets. Never overwrites an existing file.
// Usage: node scripts/gen-env.mjs
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';

const target = new URL('../.env', import.meta.url);
if (existsSync(target)) {
  console.error(
    '.env already exists — refusing to overwrite. Delete it first if you really want new secrets.',
  );
  process.exit(1);
}

const hex = (n) => randomBytes(n).toString('hex');
const pgPassword = hex(18);

writeFileSync(
  target,
  `# Generated by scripts/gen-env.mjs — local secrets, never commit.
NODE_ENV=development
LOG_LEVEL=info
PUBLIC_ORIGIN=http://localhost:5173

POSTGRES_PASSWORD=${pgPassword}
DATABASE_URL=postgres://mc:${pgPassword}@127.0.0.1:55432/mc
REDIS_URL=redis://127.0.0.1:56379

SESSION_SECRET=${hex(32)}
PII_ENCRYPTION_KEY=${randomBytes(32).toString('base64')}
PHONE_HASH_PEPPER=${hex(32)}

# ADR-004: console (OTP in API log) | demo-inbox (admin SMS inbox) | http (the organisers' own gateway)
SMS_PROVIDER=console
# console/demo-inbox need DEMO_MODE=true when NODE_ENV=production. Never set it at the real event.
DEMO_MODE=false
# SMS_PROVIDER=http only:
SMS_HTTP_URL=
SMS_HTTP_AUTH_HEADER=
SMS_HTTP_BODY_TEMPLATE=
# Extra browser origins allowed to POST (comma separated), e.g. http://localhost:8080
EXTRA_ORIGINS=

# Full Docker stack (pnpm stack:up)
STACK_NODE_ENV=development
STACK_PUBLIC_ORIGIN=http://localhost:8080
# Tunnel: Cloudflare named tunnel token (Zero Trust > Networks > Tunnels). Route hostname -> http://caddy:80
CLOUDFLARE_TUNNEL_TOKEN=
# Fallback tunnel (--profile tunnel-ngrok)
NGROK_AUTHTOKEN=
NGROK_DOMAIN=
`,
  { mode: 0o600 },
);
console.log('Wrote .env with fresh secrets (mode 600).');
